from flask import Blueprint, render_template, request, redirect, url_for, flash, session, jsonify
from routes.auth_routes import login_required, role_required
from services.pengajuan_service import PengajuanService
from services.penduduk_service import PendudukService
from services.layanan_service import LayananService

pengajuan_bp = Blueprint('pengajuan', __name__)

@pengajuan_bp.route('/pengajuan')
@login_required
def index():
    """Lists applications, incorporating textual search logic."""
    try:
        search = request.args.get('search', '').strip()
        items = PengajuanService.get_all(search_query=search if search else None)
        return render_template('pengajuan/index.html', items=items, search=search)
    except Exception as e:
        flash(f"Gagal memuat berkas pengajuan: {str(e)}", "danger")
        return render_template('pengajuan/index.html', items=[], search="")

@pengajuan_bp.route('/pengajuan/tambah', methods=['GET', 'POST'])
@login_required
@role_required(['ADMIN', 'PETUGAS'])
def create():
    """Form to submit application. Pre-evaluates constraints using Oracle PL/SQL Functions."""
    try:
        citizens = PendudukService.get_all()
        services = LayananService.get_all(only_active=True)
        
        if request.method == 'POST':
            id_penduduk = request.form.get('id_penduduk', '')
            id_layanan = request.form.get('id_layanan', '')
            catatan = request.form.get('catatan', '').strip()
            id_petugas = session.get('id_petugas')
            
            if not id_penduduk or not id_layanan:
                flash("Pemohon dan layanan wajib didefinisikan!", "warning")
                return render_template('pengajuan/create.html', citizens=citizens, services=services)
                
            try:
                # Creates application. Oracle pre-flight functions (boleh_mengajukan & cek_layanan_aktif)
                # are invoked in service. Database constraints and validations are caught.
                new_id = PengajuanService.create(id_penduduk, id_petugas, id_layanan, catatan)
                flash(f"Berkas pengajuan administrasi berhasil dibuat! (ID Transaksi: {new_id})", "success")
                return redirect(url_for('pengajuan.index'))
            except Exception as e:
                err_msg = str(e)
                # Parse out customer oracle application errors generated by function/triggers
                if "TIDAK_BOLEH" in err_msg or "VALIDASI GAGAL" in err_msg or "ORA-200" in err_msg:
                    clean_msg = err_msg.split(":")[-1].strip() if ":" in err_msg else err_msg
                    flash(f"Validasi Oracle Gagal: {clean_msg}", "warning")
                else:
                    flash(f"Sistem Oracle Gagal memproses pengajuan: {err_msg}", "danger")
                    
        return render_template('pengajuan/create.html', citizens=citizens, services=services)
    except Exception as e:
        flash(f"Gagal memetakan formulir pengajuan: {str(e)}", "danger")
        return redirect(url_for('pengajuan.index'))

@pengajuan_bp.route('/pengajuan/detail/<int:id_pengajuan>')
@login_required
def detail(id_pengajuan):
    """View application dossier and chronological status history."""
    try:
        item = PengajuanService.get_by_id(id_pengajuan)
        if not item:
            flash("Berkas pengajuan tidak ditemukan!", "danger")
            return redirect(url_for('pengajuan.index'))
            
        riwayat = PengajuanService.get_riwayat(id_pengajuan)
        
        # Load statuses for updates (Administrators and officers may submit changes)
        from database.oracle_helper import execute_query
        statuses = execute_query("SELECT * FROM status_pengajuan ORDER BY id_status ASC")
        
        return render_template('pengajuan/detail.html', item=item, riwayat=riwayat, statuses=statuses)
    except Exception as e:
        flash(f"Gagal memuat berkas detail riwayat pengajuan: {str(e)}", "danger")
        return redirect(url_for('pengajuan.index'))

@pengajuan_bp.route('/pengajuan/update-status/<int:id_pengajuan>', methods=['POST'])
@login_required
@role_required(['ADMIN', 'PETUGAS'])
def update_status(id_pengajuan):
    """Processes stage transitions. Invokes stored procedure: update_status_pengajuan."""
    try:
        id_status = request.form.get('id_status', '')
        catatan = request.form.get('catatan_status', '').strip()
        id_petugas = session.get('id_petugas')
        
        if not id_status or not catatan:
            flash("Status tujuan dan catatan tindak lanjut wajib diisi!", "warning")
            return redirect(url_for('pengajuan.detail', id_pengajuan=id_pengajuan))
            
        try:
            # Call SP
            PengajuanService.update_status(id_pengajuan, id_status, id_petugas, catatan)
            flash("Disposisi status kependudukan berhasil diterbitkan!", "success")
        except Exception as e:
            flash(f"Gagal melakukan transisi status berkas: {str(e)}", "danger")
            
        return redirect(url_for('pengajuan.detail', id_pengajuan=id_pengajuan))
    except Exception as e:
        flash(f"Kesalahan memproses mutasi: {str(e)}", "danger")
        return redirect(url_for('pengajuan.index'))

@pengajuan_bp.route('/api/pengajuan')
def api_pengajuan():
    try:
        items = PengajuanService.get_all()
        return jsonify(items)
    except Exception as e:
        return jsonify({
            "success": False,
            "message": f"Gagal mengambil data pengajuan: {str(e)}"
        }), 500